#!/usr/bin/env bash
# Produce a curated distribution archive of the portable harness subset.
#
# Ships ONLY the four portable trees, rooted at .claude/, plus INSTALL.md at the
# archive root. Everything project-specific (filled preferences, settings.json,
# root CLAUDE.md, context/, docs/, .env, ...) is deliberately excluded
# and regenerated by /bootstrap_to_custom_commands in the target.
#
# Usage: bash .claude/harness/scripts/make_portable_zip.sh [output_zip_path]
#   default output: ./harness_portable.zip
#
# The archive extracts to <target>/.claude/{harness,commands,agents,hooks} plus
# <target>/INSTALL.md. Never prints secrets.
set -euo pipefail

# --- Resolve repo root (git first, fall back to script location) -------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
    :
else
    # scripts/ -> harness/ -> .claude/ -> repo root
    REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
fi

CLAUDE_DIR="$REPO_ROOT/.claude"
if [ ! -d "$CLAUDE_DIR" ]; then
    echo "[FATAL] no .claude/ directory at repo root: $REPO_ROOT" >&2
    exit 1
fi

# --- Resolve output path (absolute) ------------------------------------------
OUT_ARG="${1:-$REPO_ROOT/harness_portable.zip}"
case "$OUT_ARG" in
    /*) OUT_ZIP="$OUT_ARG" ;;
    *)  OUT_ZIP="$(pwd)/$OUT_ARG" ;;
esac

# --- Explicit INCLUDE list -- the ONLY trees copied --------------------------
# Never a "copy .claude then delete" approach: an include-only copy cannot leak
# per-project files, and it means this script never names an excluded path.
PORTABLE_TREES="harness commands agents hooks"

# --- Stage into a temp dir ---------------------------------------------------
STAGING="$(mktemp -d)"
cleanup() { rm -rf "$STAGING"; }
trap cleanup EXIT

STAGED_CLAUDE="$STAGING/.claude"
mkdir -p "$STAGED_CLAUDE"

for tree in $PORTABLE_TREES; do
    src="$CLAUDE_DIR/$tree"
    if [ ! -d "$src" ]; then
        echo "[FATAL] portable tree missing from source: .claude/$tree" >&2
        exit 1
    fi
    cp -R "$src" "$STAGED_CLAUDE/$tree"
done

# Prune incidental build artifacts (compiled bytecode) from the staging tree --
# they ride inside harness/tests/ but must not ship in a distribution archive.
find "$STAGED_CLAUDE" -name '__pycache__' -type d -prune -exec rm -rf {} +
find "$STAGED_CLAUDE" -name '*.pyc' -type f -delete

# INSTALL.md also goes to the staging ROOT so the recipient sees it immediately.
INSTALL_SRC="$CLAUDE_DIR/harness/INSTALL.md"
if [ ! -f "$INSTALL_SRC" ]; then
    echo "[FATAL] INSTALL.md not found: .claude/harness/INSTALL.md" >&2
    exit 1
fi
cp "$INSTALL_SRC" "$STAGING/INSTALL.md"

# --- Safety guard: defense in depth ------------------------------------------
# Fail loudly if any .env or settings.json slipped into the staging tree.
LEAKED="$(find "$STAGING" \( -name '.env' -o -name 'settings.json' \) -print)"
if [ -n "$LEAKED" ]; then
    echo "[FATAL] refusing to emit zip -- excluded file(s) found in staging:" >&2
    # Print paths relative to staging so no absolute host paths leak.
    echo "$LEAKED" | sed "s#^$STAGING/##" >&2
    exit 1
fi

# --- Create the zip from inside staging so paths root correctly --------------
rm -f "$OUT_ZIP"
( cd "$STAGING" && zip -r -q "$OUT_ZIP" .claude INSTALL.md )

# --- Summary -----------------------------------------------------------------
echo "[DONE] curated portable harness archive written:"
echo "  output: $OUT_ZIP"
echo "  trees included (under .claude/): $PORTABLE_TREES"
echo "  plus INSTALL.md at the archive root"
echo "Note: preferences.md, settings.json, and root CLAUDE.md are intentionally"
echo "excluded -- they are regenerated per-project by /bootstrap_to_custom_commands."
